### ISSUE TITLE
Some general questions from looking over the module

### ISSUE THREAD

**Issue by ben-farnham** [quasar-team/CanModule#1]
- Why is there a parameter rtr for sendMessage() and also a function sendRemoteRequest?
- Having a function send that takes a CanMessage would be nice
- CAN-ID is 29 bit, so short is not sufficient
- The mechanism to send more than eight data bytes within sendMessage() is not reliable!
  - CANopen e.g. has a protocol for fragmented frames.
  - If such protocols are implemented within CanModule, class hierarchies should be used to avoid code duplication

**Comment by pnikiel** [comment]
Not sure to whom these questions are addressed, but perhaps I could help?


-     Why is there a parameter rtr for sendMessage() and also a function sendRemoteRequest?
Because some peculiar types of hardware (i.e. Wiener VME PS) require setting DLC (size) field along RTR flag. Therefore sendMessage evolved into a version that does data+RTR while sendRemoteRequest is RTR only (and can't support Wieners). I don't mind facing this in cleaner way.

-     Having a function send that takes a CanMessage would be nice
I already request this too, long time ago ;-)

-     CAN-ID is 29 bit, so short is not sufficient
CAN-ID is either 11 bits or 29 bits; at CERN I never saw the latter one. Formally though you are right.
 
-     The mechanism to send more than eight data bytes within sendMessage() is not reliable!
        CANopen e.g. has a protocol for fragmented frames.
        If such protocols are implemented within CanModule, class hierarchies should be used to avoid code duplication

Nobody uses sendMessage for more than 8 data bytes. In fragmented frames of CANopen CAN frames are also up to 8 bytes long, so a long transfer is sliced for 8 bytes pieces, with requests interleaved with replies, so conceptually it makes no sense to send more than 8 bytes.
In my opinion, sendMessage should serve only up to 8 data bytes, and existing loop to serve more should be removed (it's dirty either way).

**Comment by vfilimon** [comment]
_Why is there a parameter rtr for sendMessage() and also a function sendRemoteRequest?_

The CAN protocol has two different type of message for RTR and normal message with different contend. For it is logically to have two function 

_Having a function send that takes a CanMessage would be nice_
IN reality this function a little contradict to CAN protocol which is asynchronous It is not so simple to make the generic and reliable such function

_CAN-ID is 29 bit, so short is not sufficient_
Yes there is no any obstacle to use 29bit maybe it is needed to debug and change cobID to uint

_The mechanism to send more than eight data bytes within sendMessage() is not reliable!_
Yes it is better to restrict 8byte. It was made for next generation CAN protocol which apparently we are not going to use|

_CANopen e.g. has a protocol for fragmented frames.
If such protocols are implemented within CanModule, class hierarchies should be used to avoid code duplication_
No I do not agree to mix different level protocol. There are a lot of application protocols (like Wiener and Iseq which are not CANOpen

**Comment by vfilimon** [comment]
Ben I am also try to use CanModule for CANopen server

I have several small problems and one rather painful.
We are using UaTrace sink and when I created the **shared** library for CAN components It claimed to link with half of Ua Tool kit library. I rearranged the LogIt in order to avid this .

**Comment by andre-hartmann** [comment]
> Because some peculiar types of hardware (i.e. Wiener VME PS) require setting DLC (size) field along RTR flag. Therefore sendMessage evolved into a version that does data+RTR while sendRemoteRequest is RTR only (and can't support Wieners). I don't mind facing this in a cleaner way.

The general function would be `sendRemoteRequest(uint` canId, int lenght = `0),` because every CAN RTR frame has a length information which "shall be the DATA LENGTH CODE of the corresponding DATA FRAME ." [1, p. 17]

In practice, this length is *often* zero.

[1] http://can-newsletter.org/uploads/media/raw/e5740b7b5781b8960f55efcc2b93edf8.pdf

**Comment by andre-hartmann** [comment]
>> Having a function send that takes a CanMessage would be nice

> IN reality this function a little contradict to CAN protocol which is asynchronous It is not so simple to make the generic and reliable such function

What i meant was having a function `send(const CanMessage &message)` as counterpart for the received messages, which are already in the CanMessage struct.
