### ISSUE TITLE
question: should I base new development on branch CanModule-rev or master?

### ISSUE THREAD

**Issue by ben-farnham** [quasar-team/CanModule#3]
Hi,

Question for Michael/Slava: I've got some work to do on CanModule regarding building it into a stand-alone library format (shared probably), so, those changes will go into a new feature branch.

I see 2 branches for the CanModule: _master_ and _CanModule-rev_. As far as I remember, Slava's CanModule-rev branch contains fixes and refactorings that are waiting (for a while now) to be reviewed and merged to the master branch (note there is no pending pull request for this).

My question is: Assuming _CanModule-rev_ will be merged to master ~soon, should I base my feature branch on
a) CanModule-rev
b) master

I guess (a).
Cheers,
Ben

**Comment by meeludwig** [comment]
Can't **really** answer to that, but here is my 2 cents.
The difference seems that long CAN messages (multipart CAN frame stuff) is taken OUT in the newer version (April 2017). If I remeber correctly these multipart messages were not really supported. I assume Slava did some cleanup.

Why is this not merged ? Because probably the discussion about multipart CAN message support is still pending.

Maybe it is better to go for the master, and nevertheless NOT use multipart messages in ISEG (it is not used I believe). The difference is not very big in the code anyway.

**Comment by meeludwig** [comment]
OK, coming back to this. the branch ml_rc1 shold be merged to master first, then we a "formallY' developing with master. Then the message queu related changes/additions from CanModule_rev are discussed again with Slava.
so:
1. merge ml_rc1
2. new devels on master
3. evolve master , message queues ?
